export const SET_USERNAME_TERM = 'SET_USERNAME_TERM';
export const GET_API_DATA = 'GET_API_DATA';
export const SET_EMAIL_TERM = 'SET_EMAIL_TERM';
export const SET_PASSWORD_TERM = 'SET_PASSWORD_TERM';
